title: MQF Research
description: "MQF Research: Forensic Model Validation & Topological Research"
theme: minima

# Markdown settings
kramdown:
  math_engine: mathjax

# Exclude these from the build to be safe
exclude:
  - Gemfile
  - Gemfile.lock

#Enable excerpts on homepage
show_excerpts: true

# Optional: This makes the "read more" link appear
minima:
  show_excerpts: true
